# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'user-management-system' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'

  # Pods for user-management-system

  target 'user-management-systemTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'user-management-systemUITests' do
    # Pods for testing
  end

end
